name: Generate Snake

on:
  # Run automatically every day at midnight (UTC)
  schedule:
    - cron: "0 0 * * *" 
  
  # Allows you to manually run the job from the Actions tab for testing
  workflow_dispatch:

jobs:
  generate:
    permissions: 
      contents: write # This is CRITICAL. It allows the job to push the file without a manual password.
    runs-on: ubuntu-latest
    timeout-minutes: 5 # Hard stop: Kills the job if it takes > 5 mins
    
    steps:
      # Step 1: Generate the SVG files
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: blackdragoon26
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Step 2: Push the SVGs to a separate branch called "output"
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
